apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-pet-battle
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-pet-battle-api-8h0p0e
